version: "3.8"
services:
  redis:
    image: redis:7-alpine
    networks:
      - comfyui-net
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: comfyui-api:latest
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "5000:5000"
    networks:
      - comfyui-net
    volumes:
      - ./src/static:/app/src/static

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: comfyui-worker:latest
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - comfyui-net
    volumes:
      - ./src/static:/app/src/static

networks:
  comfyui-net:
    driver: bridge
    name: comfyui-net
