name: mamulengos-backend
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi==0.95.2
    - fastapi-socketio
    - uvicorn[standard]==0.34.2
    - pydantic>=1.10,<2.0
    - redis>=4.2.0
    - python-dotenv==1.0.0
    - sentry-sdk==1.19.0
    - structlog==23.3.0
    - jinja2==3.1.6
    - requests>=2.32.3
    - websocket-client
    - Pillow
    - qrcode
    - matplotlib
    - pydantic-settings==2.9.1